### PR TITLE
Inject the environment variable PERL_USE_UNSAFE_INC=1 into all Build …

### PR DESCRIPTION
**Pull request by toddr**
…scripts

https://github.com/Perl-Toolchain-Gang/Module-Build/issues/69

### CODE REVIEW

**Comment by haarg** [comment]
It would be good to make this conditional on `$ENV{PERL_USE_UNSAFE_INC} || !exists $ENV{PERL_USE_UNSAFE_INC}`.

**Comment by Leont** [comment]
It's an ugly but rather effective solution.

> It would be good to make this conditional on $ENV{PERL_USE_UNSAFE_INC} || !exists $ENV{PERL_USE_UNSAFE_INC}.

Agreed.

**Comment by toddr** [comment]
Updated patch based on your concerns.

**Comment by toddr** [comment]
For the time being, I'm cancelling this issue. It appears that solving the majority of issues with Test::Harness should make the remaining failures manageable.

**Pull request closed without merging**
