### PR TITLE
Include relative path for do so Makefile.PL will function without . i…

### PR DESCRIPTION
**Pull request by toddr**
…n @INC

### CODE REVIEW

**Comment by Leont** [comment]
Looks sensible to me

**Comment by Leont** [comment]
Actually, Build.PL probably needs the same fix.

**Comment by toddr** [comment]
The Build.PL thing isn't fatal:

```
Checking optional features...
inc_bundling_support....disabled
  requires:
    ! inc::latest is not installed

**Comment by haarg** [comment]
Even if it isn't strictly required, we should also change Build.PL for consistency.

**Comment by toddr** [comment]
updated

**Comment by dolmen** [comment]
I don't see how `do './inc/bootstrap.pl'` will change anything over `do 'inc/bootstrap.pl'`. Is the `default_inc_excludes_dot` patch adding some special treatment for paths starting with `./`?

**Comment by haarg** [comment]
perl special cases file paths starting in `/`, `./`, and `../` (and Win32 equivalents).  They are loaded directly rather than searching `@INC`.

**Comment by toddr** [comment]
For the time being, I'm cancelling this issue. It appears that solving the majority of issues with Test::Harness should make the remaining failures manageable.

**Comment by haarg** [comment]
It seems like we'd still want this change, no matter what we do with Test::Harness.

**Comment by toddr** [comment]
Based on my findings at the end of https://rt.perl.org/Public/Bug/Display.html?id=130467 I don't think we'll need this patch in core. As long as Test::Harness is merged in, we'll probably be good.

**Comment by Leont** [comment]
> Based on my findings at the end of https://rt.perl.org/Public/Bug/Display.html?id=130467 I don't think we'll need this patch in core.

I don't understand. AFAIK Module::Build doesn't install without this patch on a perl without `.` in @INC, how could we not need it?

**Comment by toddr** [comment]
>> Based on my findings at the end of https://rt.perl.org/Public/Bug/Display.html?id=130467 I don't think we'll need this patch in core.

> I don't understand. AFAIK Module::Build doesn't install without this patch on a perl without . in @INC, how could we not need it?

Gah! my bad. This one needs to go in. I confused it with the other merge case. That's pending.

**Comment by haarg** [comment]
Although the do in Build.PL will fail, that failure is ignored and it will continue.  And the bootstrap script is only needed for perl versions without Perl::OSType, version, or Module::Metadata.

I think that merging this is the correct thing to do though.

**Comment by Grinnz** [comment]
this has been merged in https://github.com/Perl-Toolchain-Gang/Module-Build/commit/bcc04c20e47352927b3b61814b55f370665fa8fe

**Pull request closed without merging**
