### PR TITLE
stop calling UNIVERSAL::isa as a function

### PR DESCRIPTION
**Pull request by karenetheridge**

### CODE REVIEW

**Comment by Leont** [comment]
I should probably look into a rebased version of this patch at some point.

**Comment by karenetheridge** [comment]
rebased!

**Comment by karenetheridge** [comment]
github closed this on me, grr...

**Comment by karenetheridge** [comment]
..because my changes in this PR were in the 0.4209 release (commit 40063bc2), apparently! :o

**Comment by Leont** [comment]
I had forgotten about that, excellent!

**Pull request closed without merging**
